name: "Is author an org member?"
description: "returns true if author is org member"
inputs:
  org:
    description: "The organization name"
    required: true
  username:
    description: "author of issue or PR"
    required: true
  token:
    description: "GitHub  token"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"