name: "Is user an org member?"
description: "triggers a webhook for all non-org members"
inputs:
  teammates:
    description: "all Railway staff"
    required: true
  username:
    description: "author of issue or PR"
    required: true
  webhook:
    description: "the webhook URL"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"